pub fn get_logo_by_system(system: &str) -> Vec<String> {
    match system {
        "Void" => vec![
            r#"          "#.to_string(),
            r#"          "#.to_string(),
            r#"    _______"#.to_string(),
            r#"    \_____ `-"#.to_string(),
            r#" /\   ___ `- \"#.to_string(),
            r#"| |  /   \  | |"#.to_string(),
            r#"| |  \___/  | |"#.to_string(),
            r#" \ `-_____  \/"#.to_string(),
            r#"  `-______\"#.to_string(),
        ],
        "Arch Linux" => vec![
            r#"        "#.to_string(),
            r#"        "#.to_string(),
            r#"      /\"#.to_string(),
            r#"     /  \"#.to_string(),
            r#"    /\   \"#.to_string(),
            r#"   /  __  \"#.to_string(),
            r#"  /  (  )  \"#.to_string(),
            r#" / __|  |__\\"#.to_string(),
            r#"/.`        `.\"#.to_string(),
            r#"              "#.to_string(),
        ],
        "Ubuntu" => vec![
            r#"          "#.to_string(),
            r#"          "#.to_string(),
            r#"         _"#.to_string(),
            r#"     ---(_)"#.to_string(),
            r#" _/  ---  \"#.to_string(),
            r#"(_) |   |"#.to_string(),
            r#"  \  --- _/"#.to_string(),
            r#"     ---(_)"#.to_string(),
        ],
        "Fedora" => vec![
            r#"           "#.to_string(),
            r#"           "#.to_string(),
            r#"      _____"#.to_string(),
            r#"     /   __)\"#.to_string(),
            r#"     |  /  \ \"#.to_string(),
            r#"  ___|  |__/ /"#.to_string(),
            r#" / (_    _)_/"#.to_string(),
            r#"/ /  |  |"#.to_string(),
            r#"\ \__/  |"#.to_string(),
            r#" \(_____/"#.to_string(),
        ],
        "Pop_OS!" => vec![
            r#"                 "#.to_string(),
            r#"                 "#.to_string(),
            r#"______"#.to_string(),
            r#"\   _ \        __"#.to_string(),
            r#" \ \ \ \      / /"#.to_string(),
            r#"  \ \_\ \    / /"#.to_string(),
            r#"   \  ___\  /_/"#.to_string(),
            r#"    \ \    _"#.to_string(),
            r#"   __\_\__(_)_"#.to_string(),
            r#"  (___________)"#.to_string(),
        ],
        "Manjaro" => vec![
            r#"              "#.to_string(),
            r#"              "#.to_string(),
            r#"||||||||| ||||"#.to_string(),
            r#"||||||||| ||||"#.to_string(),
            r#"||||      ||||"#.to_string(),
            r#"|||| |||| ||||"#.to_string(),
            r#"|||| |||| ||||"#.to_string(),
            r#"|||| |||| ||||"#.to_string(),
            r#"|||| |||| ||||"#.to_string(),
        ],
        "Linux Mint" => vec![
            r#"              "#.to_string(),
            r#"              "#.to_string(),
            r#" _____________"#.to_string(),
            r#"|_            \"#.to_string(),
            r#"  |  | _____  |"#.to_string(),
            r#"  |  | | | |  |"#.to_string(),
            r#"  |  | | | |  |"#.to_string(),
            r#"  |  \_____/  |"#.to_string(),
            r#"  \___________/"#.to_string(),
        ],
        "Alpine Linux" => vec![
            r#"        "#.to_string(),
            r#"        "#.to_string(),
            r#"      /\"#.to_string(),
            r#"     /  \"#.to_string(),
            r#"    / /\ \  /\"#.to_string(),
            r#"   / /  \ \/  \"#.to_string(),
            r#"  / /    \ \/\ \"#.to_string(),
            r#" / / /|   \ \ \ \"#.to_string(),
            r#"/_/ /_|    \_\ \_\"#.to_string(),
        ],
        _ => vec![
            r#"        "#.to_string(),
            r#"        "#.to_string(),
            r#"    ___"#.to_string(),
            r#"   (.. \"#.to_string(),
            r#"   (<> |"#.to_string(),
            r#"  //  \ \"#.to_string(),
            r#" ( |  | /|"#.to_string(),
            r#"_/\ __)/_)"#.to_string(),
            r#"\/-____\/"#.to_string(),
        ],
    }
}
